packages:
  - frontend
  - backend
  - e2e
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
